services:
  backend:
    build: ./attrition-api
    container_name: grand-line-api
    restart: unless-stopped
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: grand-line-ui
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
